### ISSUE TITLE
DupeBlacklist

### ISSUE THREAD

**Issue by rektrapper69** [meme20200/dupeplus#1]
Add a ingame blacklist command which blacklists the item in your mainhand, because i want to make a lifesteal dupe server.

**Comment by Galaxy202** [comment]
I will add that feature in the next update.
You will be able to do `/dupeplus blacklist <item>`, it will be auto complete for it to be easier. 
The blacklist command will be adding the item into the blacklist in the `config.yml`

**Comment by Galaxy202** [comment]
I will close this as I just made the update

**Comment by Sonicscream** [comment]
Would it be possible to add a config setting to optionally make the blacklist function like a whitelist? This way we could list out what we want people to be able to dupe vs what we don't want them to dupe.
